site_name: FaaSr - Serverless workflows made easy
site_url: https://faasr.github.io/FaaSr-Docs
theme:
  name: material
  logo: assets/faasr_logo.jpg
  features:
    - navigation.tabs
nav:
  - 'Home': 'index.md'
  - 'Tutorial': 'tutorial.md'
  - 'Documentation':
    - 'FaaSr workflow model': 'prog_model.md'
    - 'Tutorial': 'tutorial.md'
    - 'Setting up FaaSr-workflow repo': 'workflow_repo.md'
    - 'Creating functions': 'functions.md'
    - 'Creating and editing workflows': 'workflows.md'
    - 'Example workflows and functions': 'functionexamples.md'
    - 'Registering workflows': 'register_workflow.md'
    - 'Invoking workflows': 'invoke_workflow.md'
    - 'Retrieving logs': 'logs.md'
    - 'Concurrent invocation': 'rank.md'
    - 'Conditional invocation': 'conditional.md'
    - 'Invocation IDs': 'invocationid.md'
    - 'Package dependences': 'dependences.md'
    - 'R API reference': 'r_api.md'
    - 'Python API reference': 'py_api.md'
    - 'Creating cloud credentials': 'credentials.md'
    - 'Default values': 'defaults.md'
    - 'Advanced usage': 'advanced.md'
  - 'About': 'about.md'
  - 'Community': 'community.md'
  - 'Contact': 'contact.md'
  